In [1]:
import pandas as pd

In [2]:
file = '../../../data/compujordan/compujordan_products.csv'

In [3]:
df = pd.read_csv(file, index_col=0)

In [4]:
df.describe()

,product_code,product_name,brand,store,url,image_url,price,original_price,currency,in_stock,product_description,categories,specs
count,2977,2977,2977,2976,2975,2976,2976,249,2976,2976,2632,2975,2975
unique,2960,2973,101,2,2975,2581,317,102,2,3,1734,48,1852
top,3593,Lenovo V14-ADA AMD Ryzen 3 3250u - Business La...,Logitech,Compu Jordan,https://compujordan.com/intel-core-ultra-7-265...,https://compujordan.com/image/cache/catalog/pr...,15.0,55.0,JOD,False,Unknown,"{'PC and Laptops', 'Laptops'}",{}
freq,3,2,266,2975,1,16,83,11,2975,2111,362,360,1007

In [5]:
for i in range(3):
    print(df[df['product_code'] == '3593']['url'].iloc[i])

https://compujordan.com/dell-inspiron-3593-ci7-4g-core-i7-1065g7-laptop
https://compujordan.com/dell-inspiron-3593-ci7-core-i7-1065g7-laptop
https://compujordan.com/dell-inspiron-3593-ci5-core-i5-1035g1-laptop

In [6]:
df['url'].iloc[0]

'https://compujordan.com/intel-core-ultra-7-265k-20-core-processor-box-lga1851-up-to-5-5ghz'

In [7]:
df.head()

,product_code,product_name,brand,store,url,image_url,price,original_price,currency,in_stock,product_description,categories,specs
0,Ultra 7 265K,Intel Core Ultra 7 265K – 20-Core Processor (B...,Intel,Compu Jordan,https://compujordan.com/intel-core-ultra-7-265...,https://compujordan.com/image/cache/catalog/pr...,309.0,NaN,JOD,True,The Intel Core Ultra 7 265K is a next-generati...,"{'Computer Hardware', 'Gaming Components', 'Ga...",{}
1,Z890 GAMING X WIFI7,GIGABYTE Z890 Gaming X Wi-Fi 7 & Bluetooth DDR...,GIGABYTE,Compu Jordan,https://compujordan.com/gigabyte-z890-gaming-x...,https://compujordan.com/image/cache/catalog/pr...,219.0,NaN,JOD,True,The GIGABYTE Z890 Gaming X Wi-Fi 7 ATX Motherb...,"{'Computer Hardware', 'Gaming Components', 'Ga...",{}
2,i7-14700KF,Intel Core i7-14700KF – 14th Gen Unlocked CPU ...,Intel,Compu Jordan,https://compujordan.com/intel-core-i7-14700kf-...,https://compujordan.com/image/cache/catalog/pr...,299.0,NaN,JOD,True,The Intel Core i7-14700KF is a 14th Gen Raptor...,"{'Computer Hardware', 'Gaming Components', 'Ga...",{}
3,Core Ultra 9 285K,"Intel Core Ultra 9 285K (Series 2) – 24-Core, ...",Intel,Compu Jordan,https://compujordan.com/intel-core-ultra-9-285...,https://compujordan.com/image/cache/catalog/pr...,569.0,NaN,JOD,True,The Intel Core Ultra 9 285K (Series 2) is one ...,"{'Computer Hardware', 'Gaming Components', 'Ga...",{}
4,RTX 5070 Ti 16G SHADOW 3X OC,MSI GeForce RTX 5070 Ti 16G SHADOW 3X OC – 16G...,MSI,Compu Jordan,https://compujordan.com/msi-geforce-rtx-5070-t...,https://compujordan.com/image/cache/catalog/pr...,789.0,NaN,JOD,True,The MSI GeForce RTX 5070 Ti 16G SHADOW 3X OC i...,"{'Computer Hardware', 'Gaming Components', 'Ga...",{}

In [8]:
valid_df = df[df['in_stock'] == 'True']

In [9]:
valid_df.describe()

,product_code,product_name,brand,store,url,image_url,price,original_price,currency,in_stock,product_description,categories,specs
count,864,864,864,864,864,864,864,136,864,864,814,864,864
unique,864,863,67,1,864,832,142,69,1,1,740,39,336
top,Ultra 7 265K,Lenovo V14-ADA AMD Ryzen 3 3250u - Business La...,HAVIT,Compu Jordan,https://compujordan.com/intel-core-ultra-7-265...,https://compujordan.com/image/cache/catalog/pr...,10.0,55.0,JOD,True,Unknown,"{'Audio', 'Computer Accessories', 'Gaming', 'C...",{}
freq,1,2,163,864,1,4,41,7,864,864,39,135,527

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2977 entries, 0 to 2975
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_code         2977 non-null   object
 1   product_name         2977 non-null   object
 2   brand                2977 non-null   object
 3   store                2976 non-null   object
 4   url                  2975 non-null   object
 5   image_url            2976 non-null   object
 6   price                2976 non-null   object
 7   original_price       249 non-null    object
 8   currency             2976 non-null   object
 9   in_stock             2976 non-null   object
 10  product_description  2632 non-null   object
 11  categories           2975 non-null   object
 12  specs                2975 non-null   object
dtypes: object(13)
memory usage: 390.1+ KB