In [1]:
import pandas as pd

In [46]:
file_cj = '../../../data/compujordan/compujordan_products.csv'

In [47]:
df_cj = pd.read_csv(file_cj, index_col=1).drop(columns=['Unnamed: 0'])

In [48]:
df_cj.head()

,product_name,brand,store,url,image_url,price,original_price,currency,in_stock,product_description,categories,specs
product_code,,,,,,,,,,,,
Ultra 7 265K,Intel Core Ultra 7 265K – 20-Core Processor (B...,Intel,Compu Jordan,https://compujordan.com/intel-core-ultra-7-265...,https://compujordan.com/image/cache/catalog/pr...,309.0,NaN,JOD,True,The Intel Core Ultra 7 265K is a next-generati...,"{'Computer Hardware', 'Gaming Components', 'Ga...",{}
Z890 GAMING X WIFI7,GIGABYTE Z890 Gaming X Wi-Fi 7 & Bluetooth DDR...,GIGABYTE,Compu Jordan,https://compujordan.com/gigabyte-z890-gaming-x...,https://compujordan.com/image/cache/catalog/pr...,219.0,NaN,JOD,True,The GIGABYTE Z890 Gaming X Wi-Fi 7 ATX Motherb...,"{'Computer Hardware', 'Gaming Components', 'Ga...",{}
i7-14700KF,Intel Core i7-14700KF – 14th Gen Unlocked CPU ...,Intel,Compu Jordan,https://compujordan.com/intel-core-i7-14700kf-...,https://compujordan.com/image/cache/catalog/pr...,299.0,NaN,JOD,True,The Intel Core i7-14700KF is a 14th Gen Raptor...,"{'Computer Hardware', 'Gaming Components', 'Ga...",{}
Core Ultra 9 285K,"Intel Core Ultra 9 285K (Series 2) – 24-Core, ...",Intel,Compu Jordan,https://compujordan.com/intel-core-ultra-9-285...,https://compujordan.com/image/cache/catalog/pr...,569.0,NaN,JOD,True,The Intel Core Ultra 9 285K (Series 2) is one ...,"{'Computer Hardware', 'Gaming Components', 'Ga...",{}
RTX 5070 Ti 16G SHADOW 3X OC,MSI GeForce RTX 5070 Ti 16G SHADOW 3X OC – 16G...,MSI,Compu Jordan,https://compujordan.com/msi-geforce-rtx-5070-t...,https://compujordan.com/image/cache/catalog/pr...,789.0,NaN,JOD,True,The MSI GeForce RTX 5070 Ti 16G SHADOW 3X OC i...,"{'Computer Hardware', 'Gaming Components', 'Ga...",{}

In [49]:
file_os = '../../../data/oriental_store/oriental_store_products.csv'

In [50]:
df_os = pd.read_csv(file_os, index_col=1).drop(columns=['Unnamed: 0'])

In [51]:
df_os

,product_name,brand,store,url,image_url,price,original_price,currency,in_stock,product_description,categories,specs
product_code,,,,,,,,,,,,
D501MER,ASUS ExpertCenter D5 Mini Tower (D501MER) Busi...,ASUS,Oriental Store,https://os-jo.com/asus-expertcenter-d5-mini-to...,https://os-jo.com/image/cache/catalog/products...,599.0,NaN,JOD,True,Unknown,"{'Apple', 'Lenovo', 'Computer Systems', 'Dell'...","{'Processor Type': 'Core i7', 'Processor Gener..."
B5TQ8AA,HP OmniDesk Desktop PC (M02-0234) AMD Ryzen 7 ...,HP,Oriental Store,https://os-jo.com/hp-omnidesk-desktop-pc-m02-0...,https://os-jo.com/image/cache/catalog/products...,629.0,NaN,JOD,True,Unknown,"{'Apple', 'Lenovo', 'Computer Systems', 'Dell'...","{'Processor Type': 'AMD', 'Processor Generatio..."
BE8B1AA,HP OMEN 35L Gaming PC (DT GT16-0344) (Pre-Buil...,HP,Oriental Store,https://os-jo.com/hp-omen-35l-gaming-pc-dt-gt1...,https://os-jo.com/image/cache/catalog/products...,1169.0,NaN,JOD,True,Unknown,"{'Apple', 'Lenovo', 'Computer Systems', 'Dell'...","{'Processor': 'AMD RYZEN 7 8700F', 'Motherboar..."
BC4K6AA,HP OMEN 16L Gaming PC (DT TG03-0154) (Pre-Buil...,HP,Oriental Store,https://os-jo.com/hp-omen-16l-gaming-pc-dt-tg0...,https://os-jo.com/image/cache/catalog/products...,929.0,NaN,JOD,True,Unknown,"{'Apple', 'Lenovo', 'Computer Systems', 'Dell'...","{'Processor': 'INTEL CORE I5 14400F', 'Motherb..."
1M-285BJO-B3100UXX,"MSI Cubi 1M Mini PC, Portable Mini PC Desktop,...",MSI,Oriental Store,https://os-jo.com/msi-cubi-1m-mini-pc-portable...,https://os-jo.com/image/cache/catalog/products...,259.0,NaN,JOD,True,Unknown,"{'Apple', 'Lenovo', 'Computer Systems', 'Dell'...","{'Processor Type': 'Core 3', 'Processor Genera..."
...,...,...,...,...,...,...,...,...,...,...,...,...
CT-POM-V2,Bykski 50mm Cylindrical Reservoir - White POM ...,Bykski,Oriental Store,https://os-jo.com/bykski-50mm-cylindrical-rese...,https://os-jo.com/image/cache/catalog/products...,30.0,NaN,JOD,True,Unknown,"{'Reservoirs', 'Custom Cooling'}",{'Description': 'Bykski 50mm Cylindrical Reser...
CT-POM-V2,Bykski 50mm Cylindrical Reservoir - White POM ...,Bykski,Oriental Store,https://os-jo.com/bykski-50mm-cylindrical-rese...,https://os-jo.com/image/cache/catalog/products...,25.0,NaN,JOD,True,Unknown,"{'Reservoirs', 'Custom Cooling'}",{'Description': 'Bykski 50mm Cylindrical Reser...
CT-POM-V2,Bykski 50mm Cylindrical Reservoir - Black POM ...,Bykski,Oriental Store,https://os-jo.com/bykski-50mm-cylindrical-rese...,https://os-jo.com/image/cache/catalog/products...,35.0,NaN,JOD,True,Unknown,"{'Reservoirs', 'Custom Cooling'}",{'Description': 'Bykski 50mm Cylindrical Reser...
CT-POM-V2,Bykski 50mm Cylindrical Reservoir - Black POM ...,Bykski,Oriental Store,https://os-jo.com/bykski-50mm-cylindrical-rese...,https://os-jo.com/image/cache/catalog/products...,30.0,NaN,JOD,True,Unknown,"{'Reservoirs', 'Custom Cooling'}",{'Description': 'Bykski 50mm Cylindrical Reser...
CT-POM-V2,Bykski 50mm Cylindrical Reservoir - Black POM ...,Bykski,Oriental Store,https://os-jo.com/bykski-50mm-cylindrical-rese...,https://os-jo.com/image/cache/catalog/products...,25.0,NaN,JOD,True,Unknown,"{'Reservoirs', 'Custom Cooling'}",{'Description': 'Bykski 50mm Cylindrical Reser...

In [58]:
merged_df = pd.concat([df_cj,df_os], axis=0, ignore_index=True)

In [60]:
merged_df.describe()

,product_name,brand,store,url,image_url,price,original_price,currency,in_stock,product_description,categories,specs
count,8018,8018,8017,8016,8010,8014.0,1366.0,8017,8017,6699,8016,8016
unique,7979,147,3,8016,7000,675.0,345.0,3,5,2192,129,5695
top,Unknown,ASUS,Oriental Store,https://compujordan.com/intel-core-ultra-7-265...,https://os-jo.com/image/cache/catalog/products...,99.0,99.0,JOD,False,Unknown,"{'Gaming PC', 'AMD', 'Gaming PC, Gaming Laptop...",{}
freq,3,428,5041,1,23,133.0,31.0,8013,3796,3863,377,1741

In [62]:
merged_df['store'].unique()

array(['Compu Jordan', nan, '15.0', 'Oriental Store'], dtype=object)

In [88]:
merged_df[merged_df['product_name'] == 'Unknown']['url']

3846    https://os-jo.com/nzxt-kraken-elite-420-rgb-20...
4557    https://os-jo.com/corsair-vengeance-rgb-32gb-2...
7650    https://os-jo.com/intel-core-i7-12700-rtx-4070...
Name: url, dtype: object

In [100]:
merged_df[merged_df['store'] != 'Compu Jordan']

,product_name,brand,store,url,image_url,price,original_price,currency,in_stock,product_description,categories,specs
2965,Norton Security 360 Dlx 25gb Ar 1u 3d 12 Mo3,Nort,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2966,https://compujordan.com/norton-security-360-dl...,https://compujordan.com/image/cache/catalog/pr...,15.0,NaN,JOD,False,Unknown,"{'Anti-Virus and Utility', 'Software'}",{},NaN,NaN,NaN
2977,ASUS ExpertCenter D5 Mini Tower (D501MER) Busi...,ASUS,Oriental Store,https://os-jo.com/asus-expertcenter-d5-mini-to...,https://os-jo.com/image/cache/catalog/products...,599.0,NaN,JOD,True,Unknown,"{'Apple', 'Lenovo', 'Computer Systems', 'Dell'...","{'Processor Type': 'Core i7', 'Processor Gener..."
2978,HP OmniDesk Desktop PC (M02-0234) AMD Ryzen 7 ...,HP,Oriental Store,https://os-jo.com/hp-omnidesk-desktop-pc-m02-0...,https://os-jo.com/image/cache/catalog/products...,629.0,NaN,JOD,True,Unknown,"{'Apple', 'Lenovo', 'Computer Systems', 'Dell'...","{'Processor Type': 'AMD', 'Processor Generatio..."
2979,HP OMEN 35L Gaming PC (DT GT16-0344) (Pre-Buil...,HP,Oriental Store,https://os-jo.com/hp-omen-35l-gaming-pc-dt-gt1...,https://os-jo.com/image/cache/catalog/products...,1169.0,NaN,JOD,True,Unknown,"{'Apple', 'Lenovo', 'Computer Systems', 'Dell'...","{'Processor': 'AMD RYZEN 7 8700F', 'Motherboar..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8013,Bykski 50mm Cylindrical Reservoir - White POM ...,Bykski,Oriental Store,https://os-jo.com/bykski-50mm-cylindrical-rese...,https://os-jo.com/image/cache/catalog/products...,30.0,NaN,JOD,True,Unknown,"{'Reservoirs', 'Custom Cooling'}",{'Description': 'Bykski 50mm Cylindrical Reser...
8014,Bykski 50mm Cylindrical Reservoir - White POM ...,Bykski,Oriental Store,https://os-jo.com/bykski-50mm-cylindrical-rese...,https://os-jo.com/image/cache/catalog/products...,25.0,NaN,JOD,True,Unknown,"{'Reservoirs', 'Custom Cooling'}",{'Description': 'Bykski 50mm Cylindrical Reser...
8015,Bykski 50mm Cylindrical Reservoir - Black POM ...,Bykski,Oriental Store,https://os-jo.com/bykski-50mm-cylindrical-rese...,https://os-jo.com/image/cache/catalog/products...,35.0,NaN,JOD,True,Unknown,"{'Reservoirs', 'Custom Cooling'}",{'Description': 'Bykski 50mm Cylindrical Reser...
8016,Bykski 50mm Cylindrical Reservoir - Black POM ...,Bykski,Oriental Store,https://os-jo.com/bykski-50mm-cylindrical-rese...,https://os-jo.com/image/cache/catalog/products...,30.0,NaN,JOD,True,Unknown,"{'Reservoirs', 'Custom Cooling'}",{'Description': 'Bykski 50mm Cylindrical Reser...
8017,Bykski 50mm Cylindrical Reservoir - Black POM ...,Bykski,Oriental Store,https://os-jo.com/bykski-50mm-cylindrical-rese...,https://os-jo.com/image/cache/catalog/products...,25.0,NaN,JOD,True,Unknown,"{'Reservoirs', 'Custom Cooling'}",{'Description': 'Bykski 50mm Cylindrical Reser...